name: Release Notes no Slack

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install axios

      - name: Gerar release notes
        id: release
        run: |
          node scripts/generate-release.js > release.txt
          echo "RELEASE<<EOF" >> $GITHUB_OUTPUT
          cat release.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}

      - name: Enviar para Slack
        run: |
          curl -X POST -H "Content-type: application/json" \
          --data "{\"text\": \"${{ steps.release.outputs.RELEASE }}\"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}